# Python with PANDAS

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hario\appdata\roaming\python\python312\site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hario\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\hario\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.2.2'

In [7]:
#1.Create Dataframe
df = pd.DataFrame([11,22,33], columns = ['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [8]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [14]:
data = {
    'Name': ['Mahesh','Ramesh','Vishal','Suresh'],
    'Age': [16,18,20,22],
    'Salary': [2000, 5000,3000,4000],
}

In [15]:
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary
0  Mahesh   16    2000
1  Ramesh   18    5000
2  Vishal   20    3000
3  Suresh   22    4000

In [16]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
#2. Basic Dataframe Understanding

In [17]:
df.head(2)

     Name  Age  Salary
0  Mahesh   16    2000
1  Ramesh   18    5000

In [18]:
df.tail(2)

     Name  Age  Salary
2  Vishal   20    3000
3  Suresh   22    4000

In [19]:
df.shape

(4, 3)

In [21]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [22]:
df.rename(columns={'Salary':'Monthly_Salary'})

     Name  Age  Monthly_Salary
0  Mahesh   16            2000
1  Ramesh   18            5000
2  Vishal   20            3000
3  Suresh   22            4000

In [23]:
df

     Name  Age  Salary
0  Mahesh   16    2000
1  Ramesh   18    5000
2  Vishal   20    3000
3  Suresh   22    4000

In [24]:
df.rename(columns={'Salary':'Monthly_Salary'}, inplace = True)

In [25]:
df

     Name  Age  Monthly_Salary
0  Mahesh   16            2000
1  Ramesh   18            5000
2  Vishal   20            3000
3  Suresh   22            4000

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [27]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   19.000000     3500.000000
std     2.581989     1290.994449
min    16.000000     2000.000000
25%    17.500000     2750.000000
50%    19.000000     3500.000000
75%    20.500000     4250.000000
max    22.000000     5000.000000

In [28]:
#3. Save and Load data from csv

In [32]:
df.to_csv('Test_data.csv', index=False) # Export dataframe

In [34]:
Demo= pd.read_csv('Test_data.csv') # Import dataframe
Demo

     Name  Age  Monthly_Salary
0  Mahesh   16            8000
1  Ramesh   18            5000
2  Vishal   20            3000
3  Suresh   22            4000

In [35]:
Demo

     Name  Age  Monthly_Salary
0  Mahesh   16            8000
1  Ramesh   18            5000
2  Vishal   20            3000
3  Suresh   22            4000

In [37]:
Demo.head(2)

     Name  Age  Monthly_Salary
0  Mahesh   16            8000
1  Ramesh   18            5000

In [38]:
Demo.tail()

     Name  Age  Monthly_Salary
0  Mahesh   16            8000
1  Ramesh   18            5000
2  Vishal   20            3000
3  Suresh   22            4000

In [40]:
#4. Rows & Column - Selection 
Demo[['Name']] # single column

     Name
0  Mahesh
1  Ramesh
2  Vishal
3  Suresh

In [42]:
 Demo[['Name','Monthly_Salary']]

     Name  Monthly_Salary
0  Mahesh            8000
1  Ramesh            5000
2  Vishal            3000
3  Suresh            4000

In [44]:
# select rows
# Loc - based index
Demo.loc[Demo.Name=='Mahesh']

     Name  Age  Monthly_Salary
0  Mahesh   16            8000

In [50]:
Demo.loc[(df.Name=='Mahesh') & (df.Monthly_Salary>=5000)]

Empty DataFrame
Columns: [Name, Age, Monthly_Salary]
Index: []

In [52]:
Demo.loc[Demo.Name=='Ramesh']

     Name  Age  Monthly_Salary
1  Ramesh   18            5000